name: Build + Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: build
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go tools
        uses: actions/setup-go@v4

      - name: Run Tests
        run: |
          go test ./... -v

      - name: Build
        run: |
          go build .
